// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0BwQe2R8G4Xjfyk4gdjer7IRF6JRIv30',
    appId: '1:508976050125:web:1b66781fc3524750951e84',
    messagingSenderId: '508976050125',
    projectId: 'controle-59ed5',
    authDomain: 'controle-59ed5.firebaseapp.com',
    storageBucket: 'controle-59ed5.appspot.com',
    measurementId: 'G-XTG73EFDS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD77ZduRDtrpAWJrDa3Qd3DIyubroHT93k',
    appId: '1:508976050125:android:a794cf61f139bb7b951e84',
    messagingSenderId: '508976050125',
    projectId: 'controle-59ed5',
    storageBucket: 'controle-59ed5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnIOS4LUivuSQs2_uO2bagdTaEX8PnaGY',
    appId: '1:508976050125:ios:3301c5ae1ba2909f951e84',
    messagingSenderId: '508976050125',
    projectId: 'controle-59ed5',
    storageBucket: 'controle-59ed5.appspot.com',
    iosBundleId: 'com.example.controlemensal',
  );

}